server:
  port: 8062

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: api-gateway-server
  cloud:
    gateway:
      # Product Service Route
      routes[0]:
        id: product-service
        uri: lb://product-service
        predicates[0]: Path=/api/product/**
      # Order Service Route
      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/order/**
      # Inventory Service Route
      routes[2]:
        id: inventory-service
        uri: lb://inventory-service
        predicates[0]: Path=/api/inventory/**
      # Discovery Service Route
      routes[3]:
        id: discovery-service
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      # Discovery Static Service Route
      routes[4]:
        id: discovery-service-static
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-boot-microservices

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
            nodeValue: TRACE
    root: INFO

