server:
  port: 8089

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_service_db
    username: root
    password: Xandra-102
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

# Resilience4j Properties
resilience4j.circuitbreaker:
    instances:
      CircuitBreakerService:
        sliding-window-size: '10'
        minimum-number-of-calls: '5'
        permitted-number-of-calls-in-half-open-state: '3'
        failure-rate-threshold: '50'
        wait-duration-in-open-state: 5s
        sliding-window-type: count_based
        automatic-transition-from-open-to-half-open-enabled: 'true'
        register-health-indicator: 'true'